  name: quisgo
  description: "A new Flutter project."
  publish_to: 'none'

  version: 1.0.0+1

  environment:
    sdk: '^3.9.0'

  dependencies:
    flutter:
      sdk: flutter

    cupertino_icons: ^1.0.8

  dev_dependencies:
    flutter_test:
      sdk: flutter

    flutter_lints: ^4.0.0

  flutter:
    uses-material-design: true

    assets:
      - assets/fonts/

    fonts:
      - family: Montserrat
        fonts:
          # Thin (Paling Tipis)
          - asset: assets/fonts/Montserrat-Thin.ttf
            weight: 100
          - asset: assets/fonts/Montserrat-ThinItalic.ttf
            weight: 100
            style: italic

          # Extra-Light
          - asset: assets/fonts/Montserrat-ExtraLight.ttf
            weight: 200
          - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
            weight: 200
            style: italic

          # Light
          - asset: assets/fonts/Montserrat-Light.ttf
            weight: 300
          - asset: assets/fonts/Montserrat-LightItalic.ttf
            weight: 300
            style: italic

          # Regular (Normal)
          - asset: assets/fonts/Montserrat-Regular.ttf
            weight: 400
          - asset: assets/fonts/Montserrat-Italic.ttf
            weight: 400
            style: italic

          # Medium
          - asset: assets/fonts/Montserrat-Medium.ttf
            weight: 500
          - asset: assets/fonts/Montserrat-MediumItalic.ttf
            weight: 500
            style: italic

          # Semi-Bold
          - asset: assets/fonts/Montserrat-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
            weight: 600
            style: italic

          # Bold (Tebal)
          - asset: assets/fonts/Montserrat-Bold.ttf
            weight: 700
          - asset: assets/fonts/Montserrat-BoldItalic.ttf
            weight: 700
            style: italic

          # Extra-Bold
          - asset: assets/fonts/Montserrat-ExtraBold.ttf
            weight: 800
          - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
            weight: 800
            style: italic

          # Black (Paling Tebal)
          - asset: assets/fonts/Montserrat-Black.ttf
            weight: 900
          - asset: assets/fonts/Montserrat-BlackItalic.ttf
            weight: 900
            style: italic


